FROM php:8.2-apache

WORKDIR /var/www/html

# Laravel dependencies, pas aan indien nodig
RUN apt-get update && apt-get install -y \
    git unzip zip curl libzip-dev && \
    docker-php-ext-install zip pdo pdo_mysql

COPY . /var/www/html

EXPOSE 80
