version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zeroday-fanshop-app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
    command: sh -c "npm install && npm run build && apache2-foreground"
